### ISSUE TITLE
req.rewrite! :path => "/rack/sinatra/whatever"

### ISSUE THREAD

**Issue by orlin** [joshsusser/refraction#1]
NoMethodError: undefined method `empty?' for nil:NilClass

/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/commonlogger.rb:53:in `each'
/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/lint.rb:499:in`each'
/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/commonlogger.rb:36:in `each'
/Library/Ruby/Gems/1.8/gems/shotgun-0.4/lib/shotgun.rb:96:in`slurp'
/Library/Ruby/Gems/1.8/gems/shotgun-0.4/lib/shotgun.rb:62:in `proceed_as_child'
/Library/Ruby/Gems/1.8/gems/shotgun-0.4/lib/shotgun.rb:29:in`call!'
/Library/Ruby/Gems/1.8/gems/shotgun-0.4/lib/shotgun.rb:15:in `call'
/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in`call'
/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/chunked.rb:15:in `call'
/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/handler/mongrel.rb:64:in`process'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:159:in `process_client'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:158:in`each'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:158:in `process_client'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in`run'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `initialize'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in`new'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `run'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in`initialize'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in `new'
/Library/Ruby/Gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in`run'
/Library/Ruby/Gems/1.8/gems/rack-1.0.1/lib/rack/handler/mongrel.rb:34:in `run'
/Library/Ruby/Gems/1.8/gems/shotgun-0.4/bin/shotgun:129
/usr/bin/shotgun:19:in`load'
/usr/bin/shotgun:19

**Comment by joshsusser** [comment]
There's not enough information in this issue report to track down what's going on. Can you provide more about your configuration, like the order of your middleware stack? It may also have something to do with using Shotgun.

**Comment by orlin** [comment]
I'm using Ruby 1.8.7 Sinatra with no other middleware (except trying to replace Rack::Rewrite), and yes, I develop with Shotgun...  So that's a known issue?

**Comment by joshsusser** [comment]
Try version 0.2.0 now. It uses Rack::Request as the base for request object, and I think this fixes your issue where QUERY_STRING was nil.  Not quite set up to reproduce your error yet here, so if you can check on it that would be great.

**Comment by orlin** [comment]
The 0.2.0 fixed it, so this issue can be considered closed.  Thanks.
