### ISSUE TITLE
Scheme is always HTTP on Heroku

### ISSUE THREAD

**Issue by soffes** [joshsusser/refraction#2]
`req.scheme` seems to always be http on Heroku. I tried logging the scheme in the Refraction config and it would say http even if the completed in Rails log said https.

**Comment by soffes** [comment]
I have fixed this in [my fork](http://github.com/samsoffes/refraction). Please pull from me.

Basically, on Heroku `rack.url_scheme` is always `http`. If it is a page what should be `https` the add `HTTP_X_FORWARDED_PROTO` to the env with the correct scheme.

**Comment by joshsusser** [comment]
This is actually a deficiency in Rack itself.  I'd rather it get fixed there.  (I believe we talked about this on IRC and you agreed to that.)

**Comment by soffes** [comment]
Agreed, although we never talked on IRC about it :)

**Comment by joshsusser** [comment]
Ah, I think that was someone else with the same issue. But do open an issue with the Rack folks if this is still something that's causing a problem for you.

**Comment by soffes** [comment]
Will do. I haven't been using Refraction since switching to Rails 3, so it hasn't been on my mind :)

**Comment by soffes** [comment]
You left a comment on my commit in my fork awhile back. That's what it was.
