### ISSUE TITLE
rewrite! not working?

### ISSUE THREAD

**Issue by firebelly** [joshsusser/refraction#3]
This works:

`req.permanent! :host => 'fb.local'`

But this does not:

`req.rewrite! 'fb.local'`

Am I missing something? The syntax is identical to the example. If something is not working, I'm not quite sure how to debug the issue, so let me know what you need and I'll provide it.

**Comment by firebelly** [comment]
Bueller?

**Comment by joshsusser** [comment]
When passing a string as the rewrite! argument you'll want to use a fully specified url that begins with "http://". That's how the example in the README shows using that form.
