### ISSUE TITLE
uninitialized constant Refraction when using plugin with rails 2.3.2 app

### ISSUE THREAD

**Issue by ldenman** [joshsusser/refraction#4]
Hi,

I recently tried to use refraction as a plugin with my rails 2.3.2 app.

My effort went like this:

<pre>
$ script/plugin install git://github.com/pivotal/refraction.git
</pre>

(plugin installed, initializer added)

Add this line to my environment.rb (to try it on development):

<pre>
Rails::Initializer.run do |config|
  config.middleware.insert_before(::Rack::Lock, ::Refraction, {})
end
</pre>

<pre>
$ rake middleware
</pre>

rake aborted!
uninitialized constant Refraction

<pre>
$ script/console
</pre>

/usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:443:in `load_missing_constant':NameError: uninitialized constant Refraction
/usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:443:in`load_missing_constant':NameError: uninitialized constant ApplicationController

Any help, here? 

Thanks!

**Comment by joshsusser** [comment]
Was missing the init.rb file that was needed to automatically require refraction.rb.  Note that plugins don't get initialized until after the base environment, so you'll have to require the file manually if you want to use it there.  Doing the insert_before in environments/*.rb should work fine now, however.  The other option is to use the refraction gem and set it up in an initializer file (e.g. config/initializers/refraction.rb).
