### ISSUE TITLE
Rails 2.3.8 `load_missing_constant':NameError: uninitialized constant Refraction when including Gem via Bundler

### ISSUE THREAD

**Issue by nwp** [joshsusser/refraction#6]
I don't know if it's a Bundler issue or a Refraction issue, but when I attempt to use the Gem via Bundler, I receive an error on boot while things work fine if I include Refraction as a plugin.  I'd much prefer to use the Gem.

```
`load_missing_constant':NameError: uninitialized constant Refraction
```

My environment files includes:
    config.middleware.insert_before(::Rack::Lock, ::Refraction, {})

**Comment by johnlauck** [comment]
use config.middleware.insert_before("::Rack::Lock", "::Refraction", {})

**Comment by nwp** [comment]
That works!  Thanks so much for the suggestion.
